token:
  expiration_time: 864000000
  #secret: user_token_native_application_changed_#2
  secret: user_token_native_application_changed_#2

gateway:
  #ip: 127.0.0.1
  #  ip: 172.18.0.4
  ip: apigateway-service
